<?php $comments = $this->getListComments() ?>
<?php foreach($comments as $cm): 
 echo $cm->getDescription() ?>					
<?php endforeach; ?>


<form action="<?php echo $this->getUrl('news/index/addcomment') ?>" method="post">
    <input name="id" value="<?php echo $this->getId() ?>" type='hidden'>    
    <input name="name" type="text">
    <input name="email" type="text">
    <input name="description" type="text">
    <input type="submit">
</form>